// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg_struct

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ECMessage struct {
	ClientIp             *string  `protobuf:"bytes,1,opt,name=client_ip,json=clientIp" json:"client_ip,omitempty"`
	CgroupId             *int32   `protobuf:"varint,2,opt,name=cgroup_id,json=cgroupId" json:"cgroup_id,omitempty"`
	ReqType              *int32   `protobuf:"varint,3,opt,name=req_type,json=reqType" json:"req_type,omitempty"`
	RsrcAmnt             *uint64  `protobuf:"varint,4,opt,name=rsrc_amnt,json=rsrcAmnt" json:"rsrc_amnt,omitempty"`
	Request              *uint32  `protobuf:"varint,5,opt,name=request" json:"request,omitempty"`
	RuntimeRemaining     *int32   `protobuf:"varint,6,opt,name=runtime_remaining,json=runtimeRemaining" json:"runtime_remaining,omitempty"`
	Quota                *uint64  `protobuf:"varint,7,opt,name=quota" json:"quota,omitempty"`
	PayloadString        *string  `protobuf:"bytes,16,opt,name=payload_string,json=payloadString" json:"payload_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ECMessage) Reset()         { *m = ECMessage{} }
func (m *ECMessage) String() string { return proto.CompactTextString(m) }
func (*ECMessage) ProtoMessage()    {}
func (*ECMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *ECMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ECMessage.Unmarshal(m, b)
}
func (m *ECMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ECMessage.Marshal(b, m, deterministic)
}
func (m *ECMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ECMessage.Merge(m, src)
}
func (m *ECMessage) XXX_Size() int {
	return xxx_messageInfo_ECMessage.Size(m)
}
func (m *ECMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ECMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ECMessage proto.InternalMessageInfo

func (m *ECMessage) GetClientIp() string {
	if m != nil && m.ClientIp != nil {
		return *m.ClientIp
	}
	return ""
}

func (m *ECMessage) GetCgroupId() int32 {
	if m != nil && m.CgroupId != nil {
		return *m.CgroupId
	}
	return 0
}

func (m *ECMessage) GetReqType() int32 {
	if m != nil && m.ReqType != nil {
		return *m.ReqType
	}
	return 0
}

func (m *ECMessage) GetRsrcAmnt() uint64 {
	if m != nil && m.RsrcAmnt != nil {
		return *m.RsrcAmnt
	}
	return 0
}

func (m *ECMessage) GetRequest() uint32 {
	if m != nil && m.Request != nil {
		return *m.Request
	}
	return 0
}

func (m *ECMessage) GetRuntimeRemaining() int32 {
	if m != nil && m.RuntimeRemaining != nil {
		return *m.RuntimeRemaining
	}
	return 0
}

func (m *ECMessage) GetQuota() uint64 {
	if m != nil && m.Quota != nil {
		return *m.Quota
	}
	return 0
}

func (m *ECMessage) GetPayloadString() string {
	if m != nil && m.PayloadString != nil {
		return *m.PayloadString
	}
	return ""
}

func init() {
	proto.RegisterType((*ECMessage)(nil), "msg_struct.ECMessage")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0x3d, 0x6b, 0xf3, 0x30,
	0x14, 0x85, 0x51, 0xde, 0xf8, 0x8d, 0x2d, 0x48, 0x49, 0x45, 0x07, 0x95, 0x2e, 0xa6, 0x50, 0x30,
	0x14, 0xfa, 0x1f, 0x4a, 0xe9, 0x90, 0xa1, 0x8b, 0xda, 0x5d, 0x08, 0xfb, 0x22, 0x04, 0xd1, 0x87,
	0xaf, 0xae, 0x06, 0x8f, 0xfd, 0xe7, 0xc5, 0x72, 0x32, 0x9e, 0xe7, 0xdc, 0xfb, 0xc0, 0xe1, 0x9d,
	0xcf, 0xf6, 0x2d, 0x61, 0xa4, 0x28, 0xb8, 0xcf, 0x56, 0x67, 0xc2, 0x32, 0xd2, 0xf3, 0xef, 0x8e,
	0x77, 0x9f, 0x1f, 0x5f, 0x90, 0xb3, 0xb1, 0x20, 0x9e, 0x78, 0x37, 0x5e, 0x1c, 0x04, 0xd2, 0x2e,
	0x49, 0xd6, 0xb3, 0xa1, 0x53, 0xed, 0x06, 0xce, 0xa9, 0x96, 0x16, 0x63, 0x49, 0xda, 0x4d, 0x72,
	0xd7, 0xb3, 0xa1, 0x51, 0xed, 0x06, 0xce, 0x93, 0x78, 0xe4, 0x2d, 0xc2, 0xac, 0x69, 0x49, 0x20,
	0xff, 0xd5, 0xee, 0x80, 0x30, 0xff, 0x2c, 0xa9, 0x4a, 0x31, 0xe3, 0xa8, 0x8d, 0x0f, 0x24, 0xf7,
	0x3d, 0x1b, 0xf6, 0xaa, 0x5d, 0xc1, 0xbb, 0x0f, 0x24, 0x24, 0x5f, 0xef, 0x0a, 0x64, 0x92, 0x4d,
	0xcf, 0x86, 0xa3, 0xba, 0x45, 0xf1, 0xca, 0xef, 0xb1, 0x04, 0x72, 0x1e, 0x34, 0x82, 0x37, 0x2e,
	0xb8, 0x60, 0xe5, 0xff, 0xaa, 0x3e, 0x5d, 0x0b, 0x75, 0xe3, 0xe2, 0x81, 0x37, 0x73, 0x89, 0x64,
	0xe4, 0xa1, 0xfa, 0xb7, 0x20, 0x5e, 0xf8, 0x5d, 0x32, 0xcb, 0x25, 0x9a, 0x69, 0x9d, 0xbb, 0xfe,
	0x9f, 0xea, 0xa6, 0xe3, 0x95, 0x7e, 0x57, 0xf8, 0x17, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x17, 0xd6,
	0x29, 0x1b, 0x01, 0x00, 0x00,
}
